// Command gendocs generates docs/BEHAVIOR.md from the test suite.
//
// The tests are the specification: each test function's doc comment states a
// spec requirement (S-*, R-*, T-*, INV-*, A-*) and its body proves the
// implementation honors it. This tool extracts package and test doc comments
// with go/ast so the documentation cannot drift from what is actually
// verified — regenerate with `make docs`.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type testDoc struct {
	Name string
	Doc  string
}

type pkgDoc struct {
	Dir   string
	Doc   string
	Tests []testDoc
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	var pkgs []pkgDoc
	dirs, _ := filepath.Glob(filepath.Join(root, "internal", "*"))
	sort.Strings(dirs)
	for _, dir := range dirs {
		p := scan(dir)
		if p != nil {
			pkgs = append(pkgs, *p)
		}
	}

	var sb strings.Builder
	sb.WriteString("# Behavior — generated from the test suite\n\n")
	sb.WriteString("<!-- Generated by tools/gendocs. Do not edit: run `make docs`. -->\n\n")
	sb.WriteString("Every statement below is enforced by a named test. Spec references\n")
	sb.WriteString("(S-* semantics, R-* rules, INV-* invariants, T-* acceptance tests, A-* audit\n")
	sb.WriteString("checks) map to the specification this tool was built against.\n\n")

	total := 0
	for _, p := range pkgs {
		sb.WriteString("## " + p.Dir + "\n\n")
		if p.Doc != "" {
			sb.WriteString(quote(p.Doc) + "\n")
		}
		for _, t := range p.Tests {
			total++
			sb.WriteString("### `" + t.Name + "`\n\n")
			if t.Doc != "" {
				sb.WriteString(t.Doc + "\n\n")
			} else {
				sb.WriteString("(no doc comment)\n\n")
			}
		}
	}
	fmt.Fprintf(&sb, "---\n\n%d documented test cases across %d packages.\n", total, len(pkgs))

	out := filepath.Join(root, "docs", "BEHAVIOR.md")
	if err := os.WriteFile(out, []byte(sb.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d tests)\n", out, total)
}

// sortedPkgNames orders test packages deterministically, external (`x_test`)
// before internal (`x`), then lexically.
func sortedPkgNames(pkgs map[string]*ast.Package) []string {
	names := make([]string, 0, len(pkgs))
	for n := range pkgs {
		names = append(names, n)
	}
	sort.Slice(names, func(i, j int) bool {
		ei := strings.HasSuffix(names[i], "_test")
		ej := strings.HasSuffix(names[j], "_test")
		if ei != ej {
			return ei
		}
		return names[i] < names[j]
	})
	return names
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func scan(dir string) *pkgDoc {
	fset := token.NewFileSet()
	pkgsMap, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return nil
	}
	out := &pkgDoc{Dir: filepath.ToSlash(dir)}
	var names []string
	byName := map[string]testDoc{}
	// parser.ParseDir returns unordered maps, and a directory can hold BOTH
	// the internal (`plan`) and external (`plan_test`) test packages — so
	// "first doc comment wins" picked a random one per run and `make docs`
	// was not reproducible. Walk packages and files in a fixed order, with
	// the external test package first: its doc comment is the one written to
	// describe the package's behavior, not an internal white-box helper's.
	for _, pkgName := range sortedPkgNames(pkgsMap) {
		pkg := pkgsMap[pkgName]
		for _, fname := range sortedKeys(pkg.Files) {
			f := pkg.Files[fname]
			if f.Doc != nil && out.Doc == "" {
				out.Doc = strings.TrimSpace(f.Doc.Text())
			}
			for _, decl := range f.Decls {
				fn, ok := decl.(*ast.FuncDecl)
				if !ok || !strings.HasPrefix(fn.Name.Name, "Test") {
					continue
				}
				d := ""
				if fn.Doc != nil {
					d = strings.TrimSpace(fn.Doc.Text())
				}
				byName[fn.Name.Name] = testDoc{Name: fn.Name.Name, Doc: d}
				names = append(names, fn.Name.Name)
			}
		}
	}
	if len(names) == 0 {
		return nil
	}
	// Keep declaration order within a file set: sort by spec-tag-aware name.
	sort.SliceStable(names, func(i, j int) bool { return specKey(names[i]) < specKey(names[j]) })
	seen := map[string]bool{}
	for _, n := range names {
		if !seen[n] {
			seen[n] = true
			out.Tests = append(out.Tests, byName[n])
		}
	}
	return out
}

// specKey orders tests by their spec tag (T-1 before T-10, S before R…).
func specKey(name string) string {
	n := strings.TrimPrefix(name, "Test")
	for i := 0; i < len(n); i++ {
		if n[i] == '_' {
			tag := n[:i]
			// zero-pad trailing number for natural ordering
			j := len(tag)
			for j > 0 && tag[j-1] >= '0' && tag[j-1] <= '9' {
				j--
			}
			if j < len(tag) {
				return fmt.Sprintf("%s%04s_%s", tag[:j], tag[j:], n[i+1:])
			}
			return tag + "_" + n[i+1:]
		}
	}
	return "zzz_" + n
}

func quote(s string) string {
	var out strings.Builder
	for _, line := range strings.Split(s, "\n") {
		out.WriteString("> " + line + "\n")
	}
	return out.String()
}
